'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ResultManager

    '''<summary>
    '''FeedbackLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FeedbackLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ProgramDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProgramDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''AvailDepartmentsSqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AvailDepartmentsSqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ProgramRequiredFieldValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProgramRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''SemesterDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SemesterDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SemesterRequiredFieldValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SemesterRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''SubjectDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubjectDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''AllSubjectTaughtByFacultySqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AllSubjectTaughtByFacultySqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SubjectRequiredFieldValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubjectRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''EntryNumberDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EntryNumberDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''StudentInCurrentDepartmentSqlDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StudentInCurrentDepartmentSqlDataSource As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''EntryNumberRequiredFieldValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EntryNumberRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''StatusDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''StatusRequiredFieldValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StatusRequiredFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''Minor1MarkTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Minor1MarkTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Minor1MarkOutOfTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Minor1MarkOutOfTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Minor1MarkCustomValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Minor1MarkCustomValidator As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''Minor2MarkTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Minor2MarkTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Minor2MarkOutOfTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Minor2MarkOutOfTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Minor2MarkCustomValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Minor2MarkCustomValidator As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''AssignmentMarkTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AssignmentMarkTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AssignmentMarkOutOfTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AssignmentMarkOutOfTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AssigmentMarkCustomValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AssigmentMarkCustomValidator As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''MajorMarkTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MajorMarkTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MajorMarkOutOfTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MajorMarkOutOfTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''MajorMarkCustomValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MajorMarkCustomValidator As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''GradeEarnedDropdownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GradeEarnedDropdownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CommentTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CommentTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AddResultButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddResultButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdateResultButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateResultButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GradeSystemSqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GradeSystemSqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ResultsGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResultsGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ResultsSqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResultsSqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource
End Class
